### ISSUE TITLE
Iron Golem Spirit/ Zombie Pigman Spirit 

### ISSUE THREAD

**Issue by MunkeyMadness** [CAD97/SpawnerCraft2#6] opened 2015-07-06 00:09 UTC
When in the overworld, End, or Nether Spawners do not allow you to put iron golem spirit's in them
Same with all three places, Zombie Pigman are not allowed in the spawners. 
The Spawners create the unique shape that a spirit has been placed in them but they do not show the mob and do not spawn

**Comment by CAD97** [comment] 2015-07-09 14:28
Just got back from vacation, going to look at this now. My first guess is that the spawn conditions just aren't met in these cases you've provided, but this bares testing.

**Comment by CAD97** [comment] 2015-07-09 15:23
@MunkeyMadness On my end Iron Golems can spawn, the egg is just not textured properly. This is probably a Forge update thing: Build 1.8-11.14.3.1468 changes the way entities are handled by Forge. I'm now in the process of migrating to the new system.

(Pigmen work fine)

**Comment by CAD97** [comment] 2015-07-11 04:38
Note: Intended behavior: Iron Golems should not drop any essence, as they do not have a spawn egg. This is mostly unavoidable because I have no way of procedurally coloring the sprites when Minecraft does not provide me with a color scheme.

Current behavior (indev): all mobs drop a valid essence, just with no color.

**Comment by CAD97** [comment] 2015-07-11 05:08
Fixed. All spawners crash on current indev but that is a seperate problem because of in-dev progress on #7. This ticket is fixed in the next release version.

**Closed as completed by CAD97** 2015-07-11 05:08 UTC
Labels: bug
